// v4: access codes removed — identity = verified email (OTP). Users are added
// by the trainer; students self-verify on first entry, then take the survey.
// v8: adds Organization (multi-school foundation — one org active during
// this pilot, but every user/assignment/submission is scoped to one from
// day one so a second school can be added later without a data migration),
// AlgorithmFeedback (trainer QA on the AI's evaluation), StudyPlan (surfaces
// the pipeline's existing multi-week plan, previously never shown), and
// consentAt on User (one-time AI-processing disclosure).

export type Role = "student" | "trainer";

export interface Organization {
  id: string;
  name: string;
  createdAt: string;
}

export interface User {
  id: string;
  organizationId: string;
  name: string;
  email: string;
  role: Role;
  plan: "premium_pilot" | "premium" | "gold";
  verifiedAt?: string; // set on first successful email confirmation
  consentAt?: string; // set when the user accepts the AI-processing notice
  // v9 (pilot): set only on accounts provisioned as part of the free pilot
  // week (by a trainer, via AddStudentForm) — never set on a real, paying
  // subscriber. Once past this date, self-submission pauses and the student
  // sees an optional upgrade offer. Independent of `plan`, because `plan`
  // ("gold" | "premium_pilot") is reused for both pilot grants and eventual
  // paid subscriptions of the same tier.
  pilotEndsAt?: string;
  entitlements: {
    can_self_submit: boolean;
    can_practice: boolean;
    evaluations_left: number;
  };
  intake?: {
    examType: "academic" | "general";
    goalBand: number;
    examDate: string;
    residence: string;
    referralSource: string;
    purpose: string;
    selfLevel: string;
    priorAttempts: string;
    biggestChallenge: string;
    minutesPerDay: 5 | 10 | 15;
    completedAt: string;
  };
}

export interface Assignment {
  id: string;
  organizationId: string;
  trainerId: string;
  prompt: string;
  dueDate: string;
  studentIds: string[];
  createdAt: string;
}

export interface SubmissionRecord {
  id: string;
  organizationId: string;
  studentId: string;
  assignmentId: string | null;
  prompt: string;
  essay: string;
  status: "evaluating" | "done" | "failed";
  createdAt: string;
  report?: FeedbackReport;
  sessionDir?: string;
  error?: string;
}

export interface AnnotatedError {
  error_id: string;
  excerpt: string;
  issue: string;
  correction: string;
  error_type: string;
  criterion: string;
  sentence: string;
}

export interface FocusArea {
  rank: number;
  criterion: string;
  skill_tag: string;
  current_band: number;
  target_band: number;
  summary: string;
  annotated_errors: AnnotatedError[];
}

export interface FeedbackReport {
  report_id: string;
  student_id: string;
  generated_at: string;
  score_summary: {
    holistic_band: number;
    criteria_bands: {
      task_achievement: number;
      coherence_cohesion: number;
      lexical_resource: number;
      grammatical_range_accuracy: number;
    };
    headline_message: string;
  };
  top_strengths?: string[];
  top_weaknesses?: string[];
  recommendations?: string[];
  essay_text?: string;
  broken_excerpts?: string[];
  focus_area_feedback: FocusArea[];
  closing_message?: string;
  escalate_to_human_review?: boolean;
  // v18 (session-audit Finding 2): the orchestrator's QA gate for
  // canonical_resources_not_loaded_zero_resource_run already existed and
  // already flipped escalate_to_human_review to true — but the banner that
  // renders from it only ever said "flagged as ambiguous," giving no hint
  // that the actual cause was LRET running with its lexical resources
  // unavailable. quality_notice carries a specific, plain-language reason
  // when one is recognized, so the same existing signal is finally legible
  // instead of generic. Falls back to the old generic message when unset.
  quality_notice?: string;
}

export interface BankExercise {
  exercise_id: string;
  family: string;
  family_label: string;
  cefr_level: string;
  exercise_type: string;
  prompt: string;
  choices?: string[];
  answer: string;
  explanation: string;
}

// v8: trainer's structured review of the AI's evaluation quality — trainer/
// admin-only, never shown to students. Permanent B2B tool, not pilot-only.
export interface AlgorithmFeedback {
  id: string;
  organizationId: string;
  submissionId: string;
  trainerId: string;
  overallAccuracy: "accurate" | "too_generous" | "too_harsh";
  criteriaFeedback: Record<string, "correct" | "off">;
  wrongErrorIds: string[];
  missedErrors: string;
  feedbackQualityNotes: string;
  generalNotes: string;
  createdAt: string;
}

// v8: mirrors the pipeline's existing STUDY_PLAN_V1 output (already
// generated by study_plan_engine_v1.py, previously never surfaced in the
// app). Read directly from the pipeline's per-student output file — not
// stored in our own database.
export interface StudyPlanDay {
  date?: string;
  status: "pending" | "completed" | "skipped";
  exercises_target: number;
  accuracy?: number;
}

export interface StudyPlanWeek {
  week_number: number;
  focus_criterion: string;
  focus_skills: string[];
  difficulty: "foundational" | "consolidation" | "stretch";
  reason?: string; // plain-language "why this focus" — added by our reader
  days: StudyPlanDay[];
}

export interface StudyPlan {
  student_id: string;
  goal_band: number;
  practice_minutes: number;
  practice_frequency: string;
  essay_reminder_days: number;
  total_weeks: number;
  weeks: StudyPlanWeek[];
  essay_trigger: {
    triggered: boolean;
    reason: string;
    days_since_essay: number;
    accuracy_threshold: number;
  };
  next_practice_date?: string;
  days_until_next?: number;
}

export const CRITERION_LABELS: Record<string, string> = {
  task_achievement: "Task response",
  coherence_cohesion: "Coherence & cohesion",
  lexical_resource: "Lexical resource",
  grammatical_range_accuracy: "Grammar",
};

export function overallTarget(current: number, goal?: number): number {
  const fallback = Math.min(9, current + 1.0);
  return goal && goal > current ? goal : fallback;
}

export function rubricTarget(current: number): number {
  return Math.min(8, Math.floor(current) + 1);
}

export function exercisesForMinutes(min: number): number {
  return min <= 5 ? 4 : min <= 10 ? 7 : 10;
}

// v8: plain-language explanation for why the Priority Engine picked a given
// reason code — used on the student's "Your plan" page so recommendations
// come with a reason, not just an instruction. Keys match the Gold pipeline's
// real _PRIORITY_REASONS enum (pe_to_priority_directive_v2_v4.py).
export const PRIORITY_REASON_EXPLANATIONS: Record<string, string> = {
  recurring_error: "This keeps showing up across your essays, so it's worth fixing for good.",
  high_impact_gap: "Improving this skill will move your score the most right now.",
  exam_urgency: "Your exam date is coming up, so this needs attention soon.",
  plateau_break: "You've plateaued here — a different approach should help you push through.",
  new_weakness: "This is a new pattern that showed up in your latest essay.",
};